// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace hyphenApp {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("hyphenApp.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string BottomSaveButtonBar_Save {
            get {
                return ResourceManager.GetString("BottomSaveButtonBar.Save", resourceCulture);
            }
        }
        
        public static string Common_Open {
            get {
                return ResourceManager.GetString("Common.Open", resourceCulture);
            }
        }
        
        public static string Common_Month01 {
            get {
                return ResourceManager.GetString("Common.Month01", resourceCulture);
            }
        }
        
        public static string Common_Month02 {
            get {
                return ResourceManager.GetString("Common.Month02", resourceCulture);
            }
        }
        
        public static string Common_Month03 {
            get {
                return ResourceManager.GetString("Common.Month03", resourceCulture);
            }
        }
        
        public static string Common_Month04 {
            get {
                return ResourceManager.GetString("Common.Month04", resourceCulture);
            }
        }
        
        public static string Common_Month05 {
            get {
                return ResourceManager.GetString("Common.Month05", resourceCulture);
            }
        }
        
        public static string Common_Month06 {
            get {
                return ResourceManager.GetString("Common.Month06", resourceCulture);
            }
        }
        
        public static string Common_Month07 {
            get {
                return ResourceManager.GetString("Common.Month07", resourceCulture);
            }
        }
        
        public static string Common_Month08 {
            get {
                return ResourceManager.GetString("Common.Month08", resourceCulture);
            }
        }
        
        public static string Common_Month09 {
            get {
                return ResourceManager.GetString("Common.Month09", resourceCulture);
            }
        }
        
        public static string Common_Month10 {
            get {
                return ResourceManager.GetString("Common.Month10", resourceCulture);
            }
        }
        
        public static string Common_Month11 {
            get {
                return ResourceManager.GetString("Common.Month11", resourceCulture);
            }
        }
        
        public static string Common_Month12 {
            get {
                return ResourceManager.GetString("Common.Month12", resourceCulture);
            }
        }
        
        public static string Common_Sunday {
            get {
                return ResourceManager.GetString("Common.Sunday", resourceCulture);
            }
        }
        
        public static string Common_Monday {
            get {
                return ResourceManager.GetString("Common.Monday", resourceCulture);
            }
        }
        
        public static string Common_Tuesday {
            get {
                return ResourceManager.GetString("Common.Tuesday", resourceCulture);
            }
        }
        
        public static string Common_Wednesday {
            get {
                return ResourceManager.GetString("Common.Wednesday", resourceCulture);
            }
        }
        
        public static string Common_Thursday {
            get {
                return ResourceManager.GetString("Common.Thursday", resourceCulture);
            }
        }
        
        public static string Common_Friday {
            get {
                return ResourceManager.GetString("Common.Friday", resourceCulture);
            }
        }
        
        public static string Common_Saturday {
            get {
                return ResourceManager.GetString("Common.Saturday", resourceCulture);
            }
        }
        
        public static string Common_ErrorTitle {
            get {
                return ResourceManager.GetString("Common.ErrorTitle", resourceCulture);
            }
        }
        
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common.OK", resourceCulture);
            }
        }
        
        public static string Common_OptionYes {
            get {
                return ResourceManager.GetString("Common.OptionYes", resourceCulture);
            }
        }
        
        public static string Common_OptionNo {
            get {
                return ResourceManager.GetString("Common.OptionNo", resourceCulture);
            }
        }
        
        public static string Common_Mood1 {
            get {
                return ResourceManager.GetString("Common.Mood1", resourceCulture);
            }
        }
        
        public static string Common_Mood2 {
            get {
                return ResourceManager.GetString("Common.Mood2", resourceCulture);
            }
        }
        
        public static string Common_Mood3 {
            get {
                return ResourceManager.GetString("Common.Mood3", resourceCulture);
            }
        }
        
        public static string Common_Mood4 {
            get {
                return ResourceManager.GetString("Common.Mood4", resourceCulture);
            }
        }
        
        public static string Common_Mood5 {
            get {
                return ResourceManager.GetString("Common.Mood5", resourceCulture);
            }
        }
        
        public static string dReminder_RateEczema {
            get {
                return ResourceManager.GetString("dReminder.RateEczema", resourceCulture);
            }
        }
        
        public static string dReminder_ApplySteroids {
            get {
                return ResourceManager.GetString("dReminder.ApplySteroids", resourceCulture);
            }
        }
        
        public static string dReminder_ApplyMoisturisers {
            get {
                return ResourceManager.GetString("dReminder.ApplyMoisturisers", resourceCulture);
            }
        }
        
        public static string dReminder_OtherReminder {
            get {
                return ResourceManager.GetString("dReminder.OtherReminder", resourceCulture);
            }
        }
        
        public static string dReminder_Day {
            get {
                return ResourceManager.GetString("dReminder.Day", resourceCulture);
            }
        }
        
        public static string dReminder_Week {
            get {
                return ResourceManager.GetString("dReminder.Week", resourceCulture);
            }
        }
        
        public static string dReminder_Reminder {
            get {
                return ResourceManager.GetString("dReminder.Reminder", resourceCulture);
            }
        }
        
        public static string dReminder_ReminderFor {
            get {
                return ResourceManager.GetString("dReminder.ReminderFor", resourceCulture);
            }
        }
        
        public static string dReminder_ReminderNotification {
            get {
                return ResourceManager.GetString("dReminder.ReminderNotification", resourceCulture);
            }
        }
        
        public static string Helper_Cancel {
            get {
                return ResourceManager.GetString("Helper.Cancel", resourceCulture);
            }
        }
        
        public static string Helper_TakePhoto {
            get {
                return ResourceManager.GetString("Helper.TakePhoto", resourceCulture);
            }
        }
        
        public static string Helper_ChooseFromGallery {
            get {
                return ResourceManager.GetString("Helper.ChooseFromGallery", resourceCulture);
            }
        }
        
        public static string BottomTabBar_Calendar {
            get {
                return ResourceManager.GetString("BottomTabBar.Calendar", resourceCulture);
            }
        }
        
        public static string BottomTabBar_Rate {
            get {
                return ResourceManager.GetString("BottomTabBar.Rate", resourceCulture);
            }
        }
        
        public static string BottomTabBar_Trend {
            get {
                return ResourceManager.GetString("BottomTabBar.Trend", resourceCulture);
            }
        }
        
        public static string BottomTabBar_Reminders {
            get {
                return ResourceManager.GetString("BottomTabBar.Reminders", resourceCulture);
            }
        }
        
        public static string SideBar_FamilyMembers {
            get {
                return ResourceManager.GetString("SideBar.FamilyMembers", resourceCulture);
            }
        }
        
        public static string SideBar_AddRandomPatient {
            get {
                return ResourceManager.GetString("SideBar.AddRandomPatient", resourceCulture);
            }
        }
        
        public static string SideBar_AddFamilyMember {
            get {
                return ResourceManager.GetString("SideBar.AddFamilyMember", resourceCulture);
            }
        }
        
        public static string SideBar_ChangeLanguage {
            get {
                return ResourceManager.GetString("SideBar.ChangeLanguage", resourceCulture);
            }
        }
        
        public static string TopBar_UpdateProfilePic {
            get {
                return ResourceManager.GetString("TopBar.UpdateProfilePic", resourceCulture);
            }
        }
        
        public static string DoctorListPage_EmailDear {
            get {
                return ResourceManager.GetString("DoctorListPage.EmailDear", resourceCulture);
            }
        }
        
        public static string DoctorListPage_EmailSubject {
            get {
                return ResourceManager.GetString("DoctorListPage.EmailSubject", resourceCulture);
            }
        }
        
        public static string DoctorListPage_EmailBody {
            get {
                return ResourceManager.GetString("DoctorListPage.EmailBody", resourceCulture);
            }
        }
        
        public static string DoctorListPage_EmailBody2 {
            get {
                return ResourceManager.GetString("DoctorListPage.EmailBody2", resourceCulture);
            }
        }
        
        public static string DoctorListPage_EmailWeekly {
            get {
                return ResourceManager.GetString("DoctorListPage.EmailWeekly", resourceCulture);
            }
        }
        
        public static string DoctorListPage_EmailDaily {
            get {
                return ResourceManager.GetString("DoctorListPage.EmailDaily", resourceCulture);
            }
        }
        
        public static string DoctorListPage_EmailWeeks {
            get {
                return ResourceManager.GetString("DoctorListPage.EmailWeeks", resourceCulture);
            }
        }
        
        public static string DoctorListPage_EmailDays {
            get {
                return ResourceManager.GetString("DoctorListPage.EmailDays", resourceCulture);
            }
        }
        
        public static string DoctorListPage_EmailDoctor {
            get {
                return ResourceManager.GetString("DoctorListPage.EmailDoctor", resourceCulture);
            }
        }
        
        public static string DoctorListPage_SendEmailFailTitle {
            get {
                return ResourceManager.GetString("DoctorListPage.SendEmailFailTitle", resourceCulture);
            }
        }
        
        public static string DoctorListPage_SendEmailFailMessage {
            get {
                return ResourceManager.GetString("DoctorListPage.SendEmailFailMessage", resourceCulture);
            }
        }
        
        public static string DoctorListPage_HelpTextNoDoctors {
            get {
                return ResourceManager.GetString("DoctorListPage.HelpTextNoDoctors", resourceCulture);
            }
        }
        
        public static string DoctorListPage_HelpTextSelectDoctor {
            get {
                return ResourceManager.GetString("DoctorListPage.HelpTextSelectDoctor", resourceCulture);
            }
        }
        
        public static string DoctorPage_NamePlaceholder {
            get {
                return ResourceManager.GetString("DoctorPage.NamePlaceholder", resourceCulture);
            }
        }
        
        public static string DoctorPage_EmailPlaceholder {
            get {
                return ResourceManager.GetString("DoctorPage.EmailPlaceholder", resourceCulture);
            }
        }
        
        public static string DoctorPage_ClinicPlaceholder {
            get {
                return ResourceManager.GetString("DoctorPage.ClinicPlaceholder", resourceCulture);
            }
        }
        
        public static string DoctorPage_ContactInformation {
            get {
                return ResourceManager.GetString("DoctorPage.ContactInformation", resourceCulture);
            }
        }
        
        public static string DoctorPage_Name {
            get {
                return ResourceManager.GetString("DoctorPage.Name", resourceCulture);
            }
        }
        
        public static string DoctorPage_Email {
            get {
                return ResourceManager.GetString("DoctorPage.Email", resourceCulture);
            }
        }
        
        public static string DoctorPage_OtherInfo {
            get {
                return ResourceManager.GetString("DoctorPage.OtherInfo", resourceCulture);
            }
        }
        
        public static string DoctorPage_Clinic {
            get {
                return ResourceManager.GetString("DoctorPage.Clinic", resourceCulture);
            }
        }
        
        public static string DoctorPage_Address {
            get {
                return ResourceManager.GetString("DoctorPage.Address", resourceCulture);
            }
        }
        
        public static string DoctorPage_Notes {
            get {
                return ResourceManager.GetString("DoctorPage.Notes", resourceCulture);
            }
        }
        
        public static string DoctorPage_ModifyDoctor {
            get {
                return ResourceManager.GetString("DoctorPage.ModifyDoctor", resourceCulture);
            }
        }
        
        public static string DoctorPage_AddDoctor {
            get {
                return ResourceManager.GetString("DoctorPage.AddDoctor", resourceCulture);
            }
        }
        
        public static string DoctorPage_ErrorAlertMissingFields {
            get {
                return ResourceManager.GetString("DoctorPage.ErrorAlertMissingFields", resourceCulture);
            }
        }
        
        public static string DoctorPage_ErrorAlertInvalidEmail {
            get {
                return ResourceManager.GetString("DoctorPage.ErrorAlertInvalidEmail", resourceCulture);
            }
        }
        
        public static string DoctorPage_DeleteDoctor {
            get {
                return ResourceManager.GetString("DoctorPage.DeleteDoctor", resourceCulture);
            }
        }
        
        public static string LoginPage_LoginBtn {
            get {
                return ResourceManager.GetString("LoginPage.LoginBtn", resourceCulture);
            }
        }
        
        public static string LoginPage_Welcome {
            get {
                return ResourceManager.GetString("LoginPage.Welcome", resourceCulture);
            }
        }
        
        public static string LoginPage_CreateAccount {
            get {
                return ResourceManager.GetString("LoginPage.CreateAccount", resourceCulture);
            }
        }
        
        public static string LoginPage_LoginFailTitle {
            get {
                return ResourceManager.GetString("LoginPage.LoginFailTitle", resourceCulture);
            }
        }
        
        public static string LoginPage_LoginFailMessage {
            get {
                return ResourceManager.GetString("LoginPage.LoginFailMessage", resourceCulture);
            }
        }
        
        public static string PatientEczemaPage_DeletePhoto {
            get {
                return ResourceManager.GetString("PatientEczemaPage.DeletePhoto", resourceCulture);
            }
        }
        
        public static string PatientPage_FamilyMembersParticulars {
            get {
                return ResourceManager.GetString("PatientPage.FamilyMembersParticulars", resourceCulture);
            }
        }
        
        public static string PatientPage_Photo {
            get {
                return ResourceManager.GetString("PatientPage.Photo", resourceCulture);
            }
        }
        
        public static string PatientPage_Choose {
            get {
                return ResourceManager.GetString("PatientPage.Choose", resourceCulture);
            }
        }
        
        public static string PatientPage_Name {
            get {
                return ResourceManager.GetString("PatientPage.Name", resourceCulture);
            }
        }
        
        public static string PatientPage_DateOfBirth {
            get {
                return ResourceManager.GetString("PatientPage.DateOfBirth", resourceCulture);
            }
        }
        
        public static string PatientPage_Gender {
            get {
                return ResourceManager.GetString("PatientPage.Gender", resourceCulture);
            }
        }
        
        public static string PatientPage_GenderMale {
            get {
                return ResourceManager.GetString("PatientPage.GenderMale", resourceCulture);
            }
        }
        
        public static string PatientPage_GenderFemale {
            get {
                return ResourceManager.GetString("PatientPage.GenderFemale", resourceCulture);
            }
        }
        
        public static string PatientPage_UpdateFamilyMember {
            get {
                return ResourceManager.GetString("PatientPage.UpdateFamilyMember", resourceCulture);
            }
        }
        
        public static string PatientPage_AddFamilyMember {
            get {
                return ResourceManager.GetString("PatientPage.AddFamilyMember", resourceCulture);
            }
        }
        
        public static string PatientPage_HintHelpFirstPatient {
            get {
                return ResourceManager.GetString("PatientPage.HintHelpFirstPatient", resourceCulture);
            }
        }
        
        public static string PatientPage_HintHelpPatient {
            get {
                return ResourceManager.GetString("PatientPage.HintHelpPatient", resourceCulture);
            }
        }
        
        public static string PatientPage_UpdateProfilePic {
            get {
                return ResourceManager.GetString("PatientPage.UpdateProfilePic", resourceCulture);
            }
        }
        
        public static string PatientPage_DeleteFamilyMember {
            get {
                return ResourceManager.GetString("PatientPage.DeleteFamilyMember", resourceCulture);
            }
        }
        
        public static string PatientPage_ErrorMissingFields {
            get {
                return ResourceManager.GetString("PatientPage.ErrorMissingFields", resourceCulture);
            }
        }
        
        public static string PatientPage_ErrorInvalidDateOfBirth {
            get {
                return ResourceManager.GetString("PatientPage.ErrorInvalidDateOfBirth", resourceCulture);
            }
        }
        
        public static string PatientEczemaPhotoPage_Title {
            get {
                return ResourceManager.GetString("PatientEczemaPhotoPage.Title", resourceCulture);
            }
        }
        
        public static string PatientReminderPage_OthersPlaceHolder {
            get {
                return ResourceManager.GetString("PatientReminderPage.OthersPlaceHolder", resourceCulture);
            }
        }
        
        public static string PatientReminderPage_Title {
            get {
                return ResourceManager.GetString("PatientReminderPage.Title", resourceCulture);
            }
        }
        
        public static string PatientReminderPage_TitleAddReminder {
            get {
                return ResourceManager.GetString("PatientReminderPage.TitleAddReminder", resourceCulture);
            }
        }
        
        public static string PatientReminderPage_TitleUpdateReminder {
            get {
                return ResourceManager.GetString("PatientReminderPage.TitleUpdateReminder", resourceCulture);
            }
        }
        
        public static string PatientReminderPage_RemindMeTo {
            get {
                return ResourceManager.GetString("PatientReminderPage.RemindMeTo", resourceCulture);
            }
        }
        
        public static string PatientReminderPage_Frequency {
            get {
                return ResourceManager.GetString("PatientReminderPage.Frequency", resourceCulture);
            }
        }
        
        public static string PatientReminderPage_Starts {
            get {
                return ResourceManager.GetString("PatientReminderPage.Starts", resourceCulture);
            }
        }
        
        public static string PatientReminderPage_Ends {
            get {
                return ResourceManager.GetString("PatientReminderPage.Ends", resourceCulture);
            }
        }
        
        public static string PatientReminderPage_RemindEvery {
            get {
                return ResourceManager.GetString("PatientReminderPage.RemindEvery", resourceCulture);
            }
        }
        
        public static string PatientReminderPage_TimesOfTheDay {
            get {
                return ResourceManager.GetString("PatientReminderPage.TimesOfTheDay", resourceCulture);
            }
        }
        
        public static string PatientReminderPage_AddTime {
            get {
                return ResourceManager.GetString("PatientReminderPage.AddTime", resourceCulture);
            }
        }
        
        public static string PatientReminderPage_DaysOfTheWeek {
            get {
                return ResourceManager.GetString("PatientReminderPage.DaysOfTheWeek", resourceCulture);
            }
        }
        
        public static string PatientReminderPage_ErrorInvalideStartEndDates {
            get {
                return ResourceManager.GetString("PatientReminderPage.ErrorInvalideStartEndDates", resourceCulture);
            }
        }
        
        public static string PatientReminderPage_ErrorMissingTimeOfDay {
            get {
                return ResourceManager.GetString("PatientReminderPage.ErrorMissingTimeOfDay", resourceCulture);
            }
        }
        
        public static string PatientReminderPage_ErrorMissingDayOfWeek {
            get {
                return ResourceManager.GetString("PatientReminderPage.ErrorMissingDayOfWeek", resourceCulture);
            }
        }
        
        public static string PatientReminderPage_ErrorMissingReminderDescription {
            get {
                return ResourceManager.GetString("PatientReminderPage.ErrorMissingReminderDescription", resourceCulture);
            }
        }
        
        public static string PatientReminderPage_DeleteReminder {
            get {
                return ResourceManager.GetString("PatientReminderPage.DeleteReminder", resourceCulture);
            }
        }
        
        public static string PatientTabPage_Master {
            get {
                return ResourceManager.GetString("PatientTabPage.Master", resourceCulture);
            }
        }
        
        public static string PatientTabPage_PatientDetails {
            get {
                return ResourceManager.GetString("PatientTabPage.PatientDetails", resourceCulture);
            }
        }
        
        public static string PatientTabPage_RateAppMessage {
            get {
                return ResourceManager.GetString("PatientTabPage.RateAppMessage", resourceCulture);
            }
        }
        
        public static string PatientTabPage_RateApp {
            get {
                return ResourceManager.GetString("PatientTabPage.RateApp", resourceCulture);
            }
        }
        
        public static string PatientTabPage_RateAppRemindLater {
            get {
                return ResourceManager.GetString("PatientTabPage.RateAppRemindLater", resourceCulture);
            }
        }
        
        public static string PatientTabPage_RateAppDontRemind {
            get {
                return ResourceManager.GetString("PatientTabPage.RateAppDontRemind", resourceCulture);
            }
        }
        
        public static string UserPage_CreateAccount {
            get {
                return ResourceManager.GetString("UserPage.CreateAccount", resourceCulture);
            }
        }
        
        public static string UserPage_LoginName {
            get {
                return ResourceManager.GetString("UserPage.LoginName", resourceCulture);
            }
        }
        
        public static string UserPage_Password {
            get {
                return ResourceManager.GetString("UserPage.Password", resourceCulture);
            }
        }
        
        public static string UserPage_Cancel {
            get {
                return ResourceManager.GetString("UserPage.Cancel", resourceCulture);
            }
        }
        
        public static string UserPage_TapSave {
            get {
                return ResourceManager.GetString("UserPage.TapSave", resourceCulture);
            }
        }
        
        public static string UserPage_TermsAndConditions {
            get {
                return ResourceManager.GetString("UserPage.TermsAndConditions", resourceCulture);
            }
        }
        
        public static string UserPage_MissingFields {
            get {
                return ResourceManager.GetString("UserPage.MissingFields", resourceCulture);
            }
        }
        
        public static string UserPage_LoginAlreadyExists {
            get {
                return ResourceManager.GetString("UserPage.LoginAlreadyExists", resourceCulture);
            }
        }
        
        public static string UserPage_PasswordsMismatch {
            get {
                return ResourceManager.GetString("UserPage.PasswordsMismatch", resourceCulture);
            }
        }
        
        public static string UserTOSPage_TermsAndConditions {
            get {
                return ResourceManager.GetString("UserTOSPage.TermsAndConditions", resourceCulture);
            }
        }
        
        public static string UserTOSPage_CompletedRead {
            get {
                return ResourceManager.GetString("UserTOSPage.CompletedRead", resourceCulture);
            }
        }
        
        public static string PatientCalendarTabView_ShortSunday {
            get {
                return ResourceManager.GetString("PatientCalendarTabView.ShortSunday", resourceCulture);
            }
        }
        
        public static string PatientCalendarTabView_ShortMonday {
            get {
                return ResourceManager.GetString("PatientCalendarTabView.ShortMonday", resourceCulture);
            }
        }
        
        public static string PatientCalendarTabView_ShortTuesday {
            get {
                return ResourceManager.GetString("PatientCalendarTabView.ShortTuesday", resourceCulture);
            }
        }
        
        public static string PatientCalendarTabView_ShortWednesday {
            get {
                return ResourceManager.GetString("PatientCalendarTabView.ShortWednesday", resourceCulture);
            }
        }
        
        public static string PatientCalendarTabView_ShortThursday {
            get {
                return ResourceManager.GetString("PatientCalendarTabView.ShortThursday", resourceCulture);
            }
        }
        
        public static string PatientCalendarTabView_ShortFriday {
            get {
                return ResourceManager.GetString("PatientCalendarTabView.ShortFriday", resourceCulture);
            }
        }
        
        public static string PatientCalendarTabView_ShortSaturday {
            get {
                return ResourceManager.GetString("PatientCalendarTabView.ShortSaturday", resourceCulture);
            }
        }
        
        public static string PatientCalendarTabView_Calendar {
            get {
                return ResourceManager.GetString("PatientCalendarTabView.Calendar", resourceCulture);
            }
        }
        
        public static string PatientCalendarTabView_TapDate {
            get {
                return ResourceManager.GetString("PatientCalendarTabView.TapDate", resourceCulture);
            }
        }
        
        public static string PatientEczemaTabView_RateFeeling {
            get {
                return ResourceManager.GetString("PatientEczemaTabView.RateFeeling", resourceCulture);
            }
        }
        
        public static string PatientEczemaTabView_DoctorHint {
            get {
                return ResourceManager.GetString("PatientEczemaTabView.DoctorHint", resourceCulture);
            }
        }
        
        public static string PatientEczemaTabView_Photos {
            get {
                return ResourceManager.GetString("PatientEczemaTabView.Photos", resourceCulture);
            }
        }
        
        public static string PatientEczemaTabView_AddPhoto {
            get {
                return ResourceManager.GetString("PatientEczemaTabView.AddPhoto", resourceCulture);
            }
        }
        
        public static string PatientEczemaTabView_WhatDidYouDo {
            get {
                return ResourceManager.GetString("PatientEczemaTabView.WhatDidYouDo", resourceCulture);
            }
        }
        
        public static string PatientEczemaTabView_ApplySteroids {
            get {
                return ResourceManager.GetString("PatientEczemaTabView.ApplySteroids", resourceCulture);
            }
        }
        
        public static string PatientEczemaTabView_ApplyMoisturiser {
            get {
                return ResourceManager.GetString("PatientEczemaTabView.ApplyMoisturiser", resourceCulture);
            }
        }
        
        public static string PatientEczemaTabView_Others {
            get {
                return ResourceManager.GetString("PatientEczemaTabView.Others", resourceCulture);
            }
        }
        
        public static string PatientEczemaTabView_Notes {
            get {
                return ResourceManager.GetString("PatientEczemaTabView.Notes", resourceCulture);
            }
        }
        
        public static string PatientEczemaTabView_PickPhoto {
            get {
                return ResourceManager.GetString("PatientEczemaTabView.PickPhoto", resourceCulture);
            }
        }
        
        public static string PatientEczemaTabView_RateEczema {
            get {
                return ResourceManager.GetString("PatientEczemaTabView.RateEczema", resourceCulture);
            }
        }
        
        public static string PatientEczemaTabView_DeleteRecord {
            get {
                return ResourceManager.GetString("PatientEczemaTabView.DeleteRecord", resourceCulture);
            }
        }
        
        public static string PatientReminderListTabView_FrequencyTypeLabel {
            get {
                return ResourceManager.GetString("PatientReminderListTabView.FrequencyTypeLabel", resourceCulture);
            }
        }
        
        public static string PatientReminderListTabView_TimesOfDayLabel {
            get {
                return ResourceManager.GetString("PatientReminderListTabView.TimesOfDayLabel", resourceCulture);
            }
        }
        
        public static string PatientReminderListTabView_DaysOfWeekLabel {
            get {
                return ResourceManager.GetString("PatientReminderListTabView.DaysOfWeekLabel", resourceCulture);
            }
        }
        
        public static string PatientReminderListTabView_Reminders {
            get {
                return ResourceManager.GetString("PatientReminderListTabView.Reminders", resourceCulture);
            }
        }
        
        public static string PatientReminderListTabView_HintHelp {
            get {
                return ResourceManager.GetString("PatientReminderListTabView.HintHelp", resourceCulture);
            }
        }
        
        public static string PatientTrendChartTabView_Days {
            get {
                return ResourceManager.GetString("PatientTrendChartTabView.Days", resourceCulture);
            }
        }
        
        public static string PatientTrendChartTabView_Weeks {
            get {
                return ResourceManager.GetString("PatientTrendChartTabView.Weeks", resourceCulture);
            }
        }
        
        public static string PatientTrendChartTabView_ShowTheLast {
            get {
                return ResourceManager.GetString("PatientTrendChartTabView.ShowTheLast", resourceCulture);
            }
        }
        
        public static string PatientTrendChartTabView_EmailDoctor {
            get {
                return ResourceManager.GetString("PatientTrendChartTabView.EmailDoctor", resourceCulture);
            }
        }
        
        public static string PatientTrendChartTabView_HintHelp {
            get {
                return ResourceManager.GetString("PatientTrendChartTabView.HintHelp", resourceCulture);
            }
        }
        
        public static string PatientTrendChartTabView_Photos {
            get {
                return ResourceManager.GetString("PatientTrendChartTabView.Photos", resourceCulture);
            }
        }
        
        public static string PatientTrendChartTabView_ViewRecord {
            get {
                return ResourceManager.GetString("PatientTrendChartTabView.ViewRecord", resourceCulture);
            }
        }
        
        public static string PatientTrendChartTabView_NoPhotos {
            get {
                return ResourceManager.GetString("PatientTrendChartTabView.NoPhotos", resourceCulture);
            }
        }
        
        public static string PatientTrendChartTabView_ViewChart {
            get {
                return ResourceManager.GetString("PatientTrendChartTabView.ViewChart", resourceCulture);
            }
        }
        
        public static string PatientTrendChartTabView_WeeklyAverage {
            get {
                return ResourceManager.GetString("PatientTrendChartTabView.WeeklyAverage", resourceCulture);
            }
        }
        
        public static string PatientTrendChartTabView_Daily {
            get {
                return ResourceManager.GetString("PatientTrendChartTabView.Daily", resourceCulture);
            }
        }
        
        public static string PatientTrendChartTabView_EczemaChartFor {
            get {
                return ResourceManager.GetString("PatientTrendChartTabView.EczemaChartFor", resourceCulture);
            }
        }
    }
}
